"api":
  - any: ["src/api/**/*"]

"test":
  - any: ["src/test/**/*"]

"frontend":
  - any: ["src/frontend/**/*"]

"infrastructure":
  - any: ["src/docker/**/*", ".github/workflows/**/*"]

"documentation":
  - any: ["**/*.md", "docs/**/*"]

"dependencies":
  - any: ["**/package.json", "**/package-lock.json", "**/*.csproj"]

"configuration":
  - any: ["**/*.json", "**/*.yml", "**/*.yaml", ".editorconfig"]
