version: '3.8'

services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  product-review-api:
    build:
      context: ../
      dockerfile: docker/Dockerfile.api
    ports:
      - "5000:8080"
    depends_on:
      - mongodb
    environment:
    - ASPNETCORE_ENVIRONMENT=Development

  # react-frontend:
  #   build: ./frontend
  #   ports:
  #     - "3000:3000"

  # scraper:
  #   build: ./scraper
  #   depends_on:
  #     - mongodb

volumes:
  mongo-data: