# docker/Dockerfile.scraper
FROM python:3.9-slim

WORKDIR /app

# Copy the requirements.txt file into the container
COPY ./scrapers/requirements.txt ./

# Install the dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy all scrapers into the container
COPY ./scrapers /app/scrapers

# Default command can be overridden in docker-compose
CMD ["python", "/src/scrapers/pocscraper/yahoo_finance_scraper.py"]
