version: '3.8'

services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  product-review-api:
    build:
      context: ../
      dockerfile: docker/Dockerfile.api
    ports:
      - "5000:8080"
    depends_on:
      - mongodb
    environment:
    - ASPNETCORE_ENVIRONMENT=Development

  product-frontend:
    build:
      context: ../
      dockerfile: docker/Dockerfile.frontend
    ports:
    - "3000:80"
    depends_on:
    - product-review-api

volumes:
  mongo-data: