name: Frontend CI

on:
  push:
    branches: [ main ]
    paths:
      - 'src/frontend/**'
      - '.github/workflows/frontend-ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/frontend/**'
      - '.github/workflows/frontend-ci.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: src/frontend/package-lock.json
        
    - name: Install dependencies
      working-directory: src/frontend
      run: npm ci
      
    - name: Lint
      working-directory: src/frontend
      run: npm run lint
      
    - name: Type check
      working-directory: src/frontend
      run: npm run type-check || true # Add this script to package.json
      
    - name: Build
      working-directory: src/frontend
      run: npm run build