name: "Pull Request Labeler"
on: pull_request_target

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write # Ensure the action has write access to pull requests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/labeler@v5 # Use the latest version of the labeler action
        with:
          sync-labels: true
